### ISSUE TITLE
Should `git commit push` generated file

### ISSUE THREAD

**Issue by aateeque** [GitTools/GitReleaseNotes#102]
Just started using this, and I don't see why it doesn't automatically commit the output file and push to git. I use this currently in TeamCity and am manually having to push and commit. Shouldn't this be part of this too?

**Comment by JakeGinnivan** [comment]
Not always, I use it to create release notes on the fly and attach to a GitHub release

**Comment by aateeque** [comment]
Would it be useful to add it as an option?

**Comment by gep13** [comment]
>@aateeque said...
Would it be useful to add it as an option?

From my point of view, I am not sure if this is a good idea.  I tend to think of tools doing one thing well, rather than trying to do everything.
