### ISSUE TITLE
BitBucket Support

### ISSUE THREAD

**Issue by Franklin89** [GitTools/GitReleaseNotes#107]
If I set the IssueTracker to BitBucket I am unable to create ReleaseNotes. The Issue #57 has been closed and merged but if I download your solution the files are not in the GitReleaseNotes project.

![image](https://cloud.githubusercontent.com/assets/4151467/18107836/e99caf78-6f09-11e6-814f-1f63e1baceef.png)

**Comment by Franklin89** [comment]
Okay found them in the GitTools.IssueTrackers project. But BitBucket seems to be missing there.

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik did the bitbucket support get removed at some point?

**Comment by GeertvanHorrik** [comment]
Not sure, I thought I implemented it, maybe on a separate branch. Will check.

**Comment by GeertvanHorrik** [comment]
I think we are confused with JIRA. We have been working on support for JIRA, not BitBucket for what I can remember (although both from Atlassian).

**Comment by JakeGinnivan** [comment]
https://github.com/GitTools/GitReleaseNotes/commit/58d0b6f937375ea761c444602574156b528fe9f1

We added it, but it seems to be gone now.

**Comment by Franklin89** [comment]
The source code is still there in the repo but not referenced in the solution. But since all the IssueTrackers got moved to a separate repo I suppose it has to be re-implemented there?

**Comment by Franklin89** [comment]
Opened an Issue on the correct repo and closing this one...

https://github.com/GitTools/GitTools.IssueTrackers/issues/7
