### ISSUE TITLE
High Prio: Unable to generate ReleaseNotes due to "SSL/TLS secure channel" exception

### ISSUE THREAD

**Issue by StefH** [GitTools/GitReleaseNotes#111]
I noticed that I was unable to generate release-notes for my project (https://github.com/WireMock-Net/WireMock.Net)

When debugging the source code from **GitReleaseNotes**, I got an exception:

> The request was aborted: Could not create SSL/TLS secure channel.

![exception](https://user-images.githubusercontent.com/249938/36944539-db2d8fc4-1f9e-11e8-870b-f1884e5b843f.png)

I could solve this by adding this line at the beginning of `Program.cs`.
``` csharp
ServicePointManager.SecurityProtocol = ServicePointManager.SecurityProtocol | SecurityProtocolType.Tls12;
```

Is this a known problem ?

**Comment by GeertvanHorrik** [comment]
Github recently deprecated one of the TLS types. This should probably be updated in this component. Interested in doing a PR?

**Comment by gep13** [comment]
@StefH @GeertvanHorrik this happened recently in GitReleaseManager as well.  The fix in that case was here:

https://github.com/GitTools/GitReleaseManager/pull/106

I imagine that it would be similar for GitReleaseNotes.

**Comment by StefH** [comment]
The fix in **GitReleaseManager** looks 100% the same as I did as work-around for this project.

I'll create a PR and in the meantime if you need a fix, you could download the fixed binary from https://github.com/WireMock-Net/WireMock.Net/blob/master/GitReleaseNotes.exe

**Comment by StefH** [comment]
PR Created

**Comment by StefH** [comment]
issue is solved

**Comment by stunney** [comment]
Is this posted to chocolatey.org yet?

**Comment by StefH** [comment]
Not yet I believe. However since a few weeks the functionality seems broken. Maybe related to https://github.com/GitTools/GitReleaseNotes/issues/121 ?
