### ISSUE TITLE
Provide different output formats

### ISSUE THREAD

**Issue by pvandervelde** [GitTools/GitReleaseNotes#36]
It would be really nice to not only have a Markdown file as the output but maybe also a text file and and XML / JSON file. The use cases for the latter two files are:
* The text file could be used to update the NuSpec file with release notes. Given that NuSpec doesn't process Markdown there is no point in formatting it in Markdown format. Raw text would probably look cleaner.
* The XML file can be parsed by other tools. In my case what I would want to do is to get a list of all issues that were closed and (in the case of using YouTrack) mark all those issues with the build and version numbers when a release is created. e.g. when creating the release for MyAwesomeTool 1.3 I would like to update all the issues that were closed in release 1.3 with the build (Fixed in build) and version numbers (Fix version).

**Comment by AnneTheAgile** [comment]
@JakeGinnivan , maybe one very small step is to pre-validate each release notes with the live editor ? http://www.semanticreleasenotes.org/#Editor

Maybe you already do that? (I did not with my PR #63  - just saw it!).

**Comment by laedit** [comment]
I had the same issue, so I made a [project](https://github.com/laedit/SemanticReleaseNotesParser/) which allow to parse and format a Semantic Release Notes.
Sadly the current version of the spec doesn't handle multiples releases on the same file, but with the current format of GitReleaseNotes they are recognized as sections.

**Comment by AnneTheAgile** [comment]
@laedit, ty! I will try it out. I got all distracted looking into the appveryor build syntax, I had not seen them before.

**Comment by GeertvanHorrik** [comment]
I think this can be merged with #55. Will close this, feel free to re-open if I am mistaken.
