### ISSUE TITLE
Provide a way to filter out certain issues from being included in release notes

### ISSUE THREAD

**Issue by pvandervelde** [GitTools/GitReleaseNotes#41]
This would be useful for tasks that are in the issue list but that don't actually contribute code, e.g. setting up a build server or cutting a release etc. etc. The YouTrack and Jira issue trackers already have that ability through their filters but the GitHub issue tracker always includes all items.

**Comment by GeertvanHorrik** [comment]
Closing this as duplicate in favor of #54
