### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by khellang** [GitTools/GitReleaseNotes#46]
I'm not able to install through Chocolatey. Here's the error:

![2014-06-26_01-11-25](https://cloud.githubusercontent.com/assets/582487/3393086/306dd69a-fcbe-11e3-8b7a-b7e0561dc4de.png)

Seems like it's because https://github.com/JakeGinnivan/GitReleaseNotes/releases/download/0.5.0/GitReleaseNotes.0.5.0.zip returns 404.

**Comment by abe545** [comment]
@JakeGinnivan it looks like this is still happening, at least for 0.5.0 and 0.6.0.

**Comment by GeertvanHorrik** [comment]
This is probably caused because we moved GitReleaseNotes to a new team project called GitTools. We hope to release a new version soon that fixes this issue.

**Comment by khellang** [comment]
Doesn't GitHub set up redirects for these scenarios?

**Comment by GeertvanHorrik** [comment]
Apparently not for the releases

**Comment by khellang** [comment]
I think everything should be redirected. I.e. `/JakeGinnivan/GitReleaseNotes/{rest-of-url*}` should automatically be redirected to `/GitTools/GitReleaseNotes/{rest-of-url*}`. Could it be that the client doesn't follow redirects?

**Comment by GeertvanHorrik** [comment]
I think I see the problem. Jake has forked the repository again (and with a fork, releases are not cloned).

**Comment by khellang** [comment]
Ah, right. From [the docs](https://help.github.com/articles/transferring-a-repository/):

> Warning: If you create a new repository under your account with the same name as the transferred repository, existing redirects to the transferred repository will break. Instead, use a different name for the new repository.

**Comment by batzen** [comment]
Would be nice if you could fix this issue.
Wasn't a nice starting experience not being able to install via chocolatey.
Would have moved on to the next alternative if I haven't seen @GeertvanHorrik name appearing here.

**Comment by khellang** [comment]
OK, something is definitely FUBAR with this repo. I just got a notification for @batzen's comment and the link pointed to `https://github.com/JakeGinnivan/GitReleaseNotes/issues/46#event-140531365`. Maybe you should contact GitHub and have them look into it?

**Comment by GeertvanHorrik** [comment]
@batzen let me know if you need help. Happy to contribute to fluent to get this up and running.

**Comment by GeertvanHorrik** [comment]
We are currently working on creating a centralized core for GitVersion / GitReleaseNotes / GitLink / etc. Once that is ready, we can release a new version and this will all be over (the redirecting issues).

**Comment by gep13** [comment]
@khellang are you talking about the notification on the GitHub website, or the link in the email that came through?  I got some emails about the new notifications, and they correctly link to this repo.

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik I think we may need to revert changes to go back to where the last release was then try and increment from there. I don't feel master is in a state we can release it as it is a pain to use and all the original docs are invalid

**Comment by JakeGinnivan** [comment]
Then we can slowly build back the new functionality in a non breaking way?

**Comment by khellang** [comment]
@gep13 GH website :smile:

**Comment by GeertvanHorrik** [comment]
@JakeGinnivan agree, I am on feature/gittools_core for a while now. Once Atlassian.Sdk supports REST (I proposed a few methods we need), then we can "finish" GitTools.Core. Can you do the revert or do you want me to do it?

**Comment by JakeGinnivan** [comment]
https://chocolatey.org/packages/GitReleaseNotes.Portable is waiting approval

**Comment by gep13** [comment]
@JakeGinnivan I have just had a look at the package, and I just have a couple comments.  Any chance you can address them, and I will get the package approved and marked as trusted.

**Comment by JakeGinnivan** [comment]
Yep! Will do

Sent from my Windows Phone
________________________________
