### ISSUE TITLE
Consider allowing remote repositories

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitReleaseNotes#53]
I have implemented support for remote git repositories in both GitVersion and GitHubLink. I think that could be a great addition to this project as well. Maybe if I find some time next week I will try to create a pull request.

**Comment by dazinator** [comment]
:+1:

**Comment by dazinator** [comment]
As I also needed this feature, and as @GeertvanHorrik has already done most of the hard work in other projects, I thought I'd have a go at moving this accross and refactoring it in. I'll submit a PR for you to do with what you will, assuming I succeed :)

**Comment by dazinator** [comment]
Have submitted PR #64

**Comment by GeertvanHorrik** [comment]
Works. Thanks for the contribution @dazinator
