### ISSUE TITLE
Jira support is broken

### ISSUE THREAD

**Issue by JonCubed** [GitTools/GitReleaseNotes#67]
I am getting the following exception when I try it with Jira.
'RestSharp.JsonObject' does not contain a definition for 'issues'

After a bit of research it seems that the RestSharp NuGet has deserialising to dynamics off, [see line 29] (https://github.com/restsharp/RestSharp/blob/master/RestSharp/SimpleJson.cs#L29).

**Comment by JakeGinnivan** [comment]
I am not against changing the json parser to one which will work better. Otherwise happy to get a PR with the changes required to make RestSharp work

**Comment by JonCubed** [comment]
I've switched it to JSON.NET in my fork, but I have a bunch of jira fixes in the works so PR after I finish those off.

**Comment by GeertvanHorrik** [comment]
I am having this issue as well. Will do a PR if I can get this fixed.

**Comment by GeertvanHorrik** [comment]
@JakeGinnivan did you not use the Atlassian SDK for a reason?

**Comment by JakeGinnivan** [comment]
Nope, didn't realise it existed when I looked. News to me that it exists now actually :P

**Comment by GeertvanHorrik** [comment]
I used it in JiraCli (see https://github.com/catenalogic/jiracli), will create PR with that usage. Then we can query the "closed" status so it will work on each system

**Comment by JakeGinnivan** [comment]
Great, thanks

**Comment by GeertvanHorrik** [comment]
This is fixed now.

**Comment by JonCubed** [comment]
Just looked at the SDK, it has uses the deprecated SOAP API for jira which has a major bug in regards to JQL, It will only ever get the first maxIssues. 

I thought a workaround could be to get the count of issues the jql returns but doesn't seem to be a way to do it.

**Comment by GeertvanHorrik** [comment]
The prerelease for the SDK dates from 2013, but the stable version dates from December 2014. That contains the bug?

**Comment by JonCubed** [comment]
yeah its the Jira SOAP API that doesn't support it, so nothing the SDK can do to fix it unless they switch to the REST API

**Comment by JonCubed** [comment]
found [Jira Rest Client](https://github.com/techtalk/JiraRestClient), I've added a couple of pull requests to match the needed functionality.

If your happy I'll add a PR for swapping over to it once they are merged.

**Comment by GeertvanHorrik** [comment]
That would be great. We will await the pr. Thanks!
