### ISSUE TITLE
Create improvements to improve usability

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitReleaseNotes#73]
Created based on this issue: https://github.com/JakeGinnivan/GitReleaseNotes/issues/67

Tasks for this issue:

1) ~~Add context classes (context might have more than just the arguments specified, and allows easier understanding how things work)~~
2) ~~Use Atlassian SDK instead of manual json requests~~
3) Add logger (ILogger) so the exe can be referenced and used without command line. I am thinking of creating a web service where I can ask the release notes automatically for any version of any product we create.

**Comment by JakeGinnivan** [comment]
Nice idea with the service! I am happy to put it up on Azure when we get it working

**Comment by GeertvanHorrik** [comment]
Yes, we are planning to create an automated "what's new" section into all of our apps which call a webservice that generates (and caches) release notes. Thing is that it's too tightly coupled to console apps for now, but I will try to prepare as much as possible.

**Comment by JakeGinnivan** [comment]
Agreed, I was planning to take a decent run at this. If you can sort the Jira stuff then I can have a crack at separating it out.

I would want the service to also take into account the releasenotes file in the repo so it appends, allowing you to customise the output as you are building a release. 

What sort of workflow are you thinking with the service?

**Comment by GeertvanHorrik** [comment]
We have desktop software apps. We have major versions and prereleases (we use GitVersion for version determination, Squirrel for deployment). 

What I want is the following:

1) After every update, show a "welcome, these are the changes". For delta versions, this would be the delta from the previous release to the current release
2) For major versions, it should show the release notes for the major version only

This way our testers / beta users can easily see what's need (can they test the resolved issues) and we can inform the users when they upgraded as well.

**Comment by JakeGinnivan** [comment]
I guess with Jira you can use the closed reason and only show fixed/resolved but not wont fix and duplicate etc?

**Comment by GeertvanHorrik** [comment]
New workflows in jira are simpler and don't have too many closed statuses. Since you can fully customize any status (and tell if it represents a "closed" status) in jira, we can query them first to dynamically set up the default JQL. Currently working on that.

**Comment by JakeGinnivan** [comment]
A problem I have with GitHub is closed issues which are discussions, not bugs etc. I need to delete them out of the release notes which are generated. If it is generated on the fly how do you keep it clean?

**Comment by GeertvanHorrik** [comment]
For me the focus is JIRA (I don't touch anything else). I think GitHub needs a discussion forum, if they don't fix that, we can't prevent that. Maybe we can check tags, but that's for later. For today the focus is moving to context and make sure Jira generates some decent release notes.

**Comment by JakeGinnivan** [comment]
:+1:
