### ISSUE TITLE
Use Issue.FixVersions to determine the fix version instead of the date/time of a commit

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitReleaseNotes#85]
GitTools.IssueTrackers supports FixVersions to specify in what version an issue is fixed. This way it should automatically be possible to correctly generate the release notes.

**Comment by JakeGinnivan** [comment]
This needs to be a strategy, using milestones should not be required for GitHub

**Comment by GeertvanHorrik** [comment]
What do you mean by that? When I specify JIRA, it has milestones / fixversions, but we can still combine stuff. For example, I am testing this on Catel, and 3.8.1 should have only 1 fix (hotfix release), still it has this:

```
3.8.1 (2013-12-12T18:36:22+01:00)
[CTL-264] Reset FileServiceBase.ValidateNames default value to true
[CTL-261] Replace all instances of RegisterDebugListener with AddDebugListener
[CTL-260] Remove ExposeAttribute unit tests because marked as error in 3.9
[CTL-259] Rename defines in Windows Phone 8 projects from WP8 to WP80
[CTL-204] Catel.IoC.IServiceLocator should contains some methord to remove registered type
```

**Comment by GeertvanHorrik** [comment]
So we should either:

1) Accept issues from the issue tracker (we assume that the issue tracker is always right)
2) Add additional mentioned issues inside commits that are inside a tag AND are closed (might be a partial commit)

**Comment by JakeGinnivan** [comment]
I should be able to run this tool against a github repository which is *not* using milestones or mentioning issue numbers in commits

**Comment by GeertvanHorrik** [comment]
Then this will happen:

1) No issues found (because no milestones)
2) Issues are mentioned in commits, so these are gathered

Works perfect, right?

**Comment by JakeGinnivan** [comment]
I used GitReleaseNotes to generate https://github.com/ParticularLabs/GitVersion/releases/tag/3.0.0-Beta3

We don't use milestones or mention commits and the tool works fine. We cannot remove that functionality

**Comment by GeertvanHorrik** [comment]
Then the title might have mislead you a bit. It will always be a combination of 2:

1) Use issue tracker (in case people forget to mention an issue)
2) Use commits (which is a fallback in case 1 is not available)

**Comment by JakeGinnivan** [comment]
https://github.com/ParticularLabs/GitVersion/releases/tag/3.0.0-Beta3 includes pull requests and issues, it is not using commits?

**Comment by GeertvanHorrik** [comment]
It finds the issues because they are being mentioned inside the commit titles, so using commits, right?

**Comment by JakeGinnivan** [comment]
Nope, many of those issues do not mention issues. It works by getting all closed issues between the timestamp of the last git tag and the current git tag or now

**Comment by JakeGinnivan** [comment]
Here is the logic I think we need for generating a complete release notes (all releases):

1) Gather all release versions, this is from tags and the issue tracker (completed releases/milestones). Versions from the tracker should win over tags
2) Get issues closed between closing the previous version and closing the current version
3) Get issues tagged with fix version/in milestone
4) Combine 2 & 3 removing duplicates

**Comment by GeertvanHorrik** [comment]
On all branches or a specific branch where the tags are used?

**Comment by JakeGinnivan** [comment]
GitReleaseNotes gets run against a branch, so all tags on that branch

**Comment by GeertvanHorrik** [comment]
2) AND are assigned to a milestone OR have no milestone at all. Otherwise it might be an issue we fixed on develop while we were fixing the hotfix (that's what happening on my test data right now).

So I think we should combine 2 and 3.

**Comment by JakeGinnivan** [comment]
That restriction makes sense where querying closed issues during a time period. Just exclude issues which have a milestone assigned.

I don't mind getting incorrect data, I manually edit/combine/remove issues anyways after I generate. The tool just does the hard work of collating the data for me

**Comment by GeertvanHorrik** [comment]
We are looking to automatically generated stuff very dynamically (if test a updates from unstable 34 - unstable 36, we want to include that so they know exactly what has happened since last time). I will try to implement it so everyone is happy.

**Comment by GeertvanHorrik** [comment]
I will close this issue, we can discuss further at #86.
