### ISSUE TITLE
Chocolatey install doesn't work

### ISSUE THREAD

**Issue by bendetat** [GitTools/GitReleaseNotes#88]
Per the install instructions, `cinst GitReleaseNotes` doesn't work. Looks like `chocolateyInstall.ps1` is pointing to `github.com/JakeGinnavan/GitReleaseNotes` instead of this repo.

![](http://i.imgur.com/9Eh1nag.png)

**Comment by JakeGinnivan** [comment]
https://chocolatey.org/packages/GitReleaseNotes.Portable has been submitted and hopefully approved soon.
